// themes.embedded.json is generated by scripts/embed.mjs (see there for the
// shape) and bundled by wrangler as a JSON module. Declared here so the Worker
// gets a stable type without tsc having to parse the multi-megabyte file.
declare module "*.embedded.json" {
  export interface EmbeddedTheme {
    id: string;
    name: string;
    description: string;
    file: string;
    isDefault: boolean;
    html: string;
  }
  export interface ThemeBundle {
    fontFaceCss: string;
    photoDataUri: string;
    themes: EmbeddedTheme[];
  }
  const bundle: ThemeBundle;
  export default bundle;
}
